version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: someprestashop
      MYSQL_DATABASE: prestashop17
      MYSQL_USER: prestashop17
      MYSQL_PASSWORD: prestashop17
  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:1.7
    volumes:
      - ./prestashop:/var/www/html
      - ./modules:/var/www/html/modules
    ports:
      - "8082:80"
    restart: always
    environment:
      DB_SERVER: db
      DB_USER: prestashop17
      DB_PASSWD: prestashop17
      DB_NAME: prestashop17
      PS_DEMO_MODE: 1
      PS_LANGUAGE: es